name: seismo-jupyterlite-benchmarks
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipykernel
  - jupyterlab
  - numpy
  - scipy
  - matplotlib
  - cartopy
  - obspy
  - psutil
  - requests
